name: "deploy"
run-name: "Deploy to server"

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker Image"]
    types:
      - completed
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to the project directory
            cd /home/kevin/projects/echo

            DOCKER_IMAGE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

            # Pull the latest Docker images
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/$DOCKER_IMAGE:latest

            # Set environment variables and start the app
            echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" > .env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            echo "REDIS_URL=localhost:6379" >> .env
            echo "PORT=8080" >> .env

            # run the docker image
            docker run -d \
              --name echo \
              --env-file .env \
              -p 8080:8080 \
              ghcr.io/$DOCKER_IMAGE:latest

            # Optional: Clean up unused images
            docker image prune -f
