name: "deploy"
run-name: "Deploy to server"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to the project directory
            cd /home/kevin/projects/echo

            # Pull the latest Docker images
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            # Set environment variables and start the app
            echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" > .env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
            echo "REDIS_URL=localhost:6379" >> .env
            echo "PORT=8080" >> .env

            # run the docker image
            docker run -d \
              --name echo \
              --env-file .env \
              -p 8080:8080 \
              dkrkev/echo:latest

            # Optional: Clean up unused images
            docker image prune -f
